# Lab 11 - Chess Board
### Adam Owada

In [1]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
from random import random

ModuleNotFoundError: No module named 'matplotlib'

In [7]:
matrix = np.zeros((8,8), dtype="int")
print(matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
